### ISSUE TITLE
Mouse+keyboard vs controller detection.

### ISSUE THREAD

**Issue by UhGoomba** [nathanhoad/godot_input_helper#29]
**Describe the feature you'd like**
I would like to have a signal that emits when I switch to using a (mouse or keyboard), or a controller of and kind.

**Describe alternatives you've considered**
I could implement this myself, I have in the past, but I was hoping this plugin would do it for me.

Thank you

**Comment by UhGoomba** [comment]
![image](https://github.com/nathanhoad/godot_input_helper/assets/53350163/9f615209-b792-49ce-bc0d-005ab086c534)
I have implemented an equivalent of this by changing this line of code. If you want me to make PR, I will. This might go against your design because it seems like you are strictly using hardware id stuff.

**Comment by UhGoomba** [comment]
I've looked at your code more, and I don't know how godot does this exactly, but maybe you could create another device with id of -1 for the mouse, and have a function that determines if your current device is kb+m or a controller.

**Comment by nathanhoad** [comment]
The lack of mouse there was unintentional. Thanks for finding that 👍

**Comment by UhGoomba** [comment]
Hey thank you for adding this, I would like to note that it might be useful to also include a deadzone for InputEventMouseMotion so that bumping your desk won't change your device.

**Comment by axipher** [comment]
> Hey thank you for adding this, I would like to note that it might be useful to also include a minimum relative change for InputEventMouseMotion so that bumping your desk won't change your device.

While I also hate when random bumps of my desk or a passing big truck vibrates my mouse just enough to move the cursor, I wouldn't use just mouse movement to trigger keyboard + mouse mode as the current primary input method.

What I did in previous mini-games I've made is not look at mouse movement, but look for an actual mouse click or keyboard press to change the primary method to keyboard + mouse.  My reason is that there is a chance you have a second screen up and if you accidentally move your mouse over the game window or use the scroll-wheel when you still have the game active would potentially change modes on you without you wanting it.

Where as specifically clicking a mouse button in the game window is much more discreet method to detect intentional mouse input by the user/player.

**Comment by UhGoomba** [comment]
I don't think mousing over the window triggers a mouse motion event, but I'll check and even if it does I think that it is okay. Personally I prefer that if I am using a controller than I use my mouse in game, it switches to keyboard+mouse mode
